#:schema node_modules/wrangler/config-schema.json
name = "vnotes"
compatibility_date = "2024-11-06"
main = "src/index.ts"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "notes-db"
database_id = "d1298061-ad2c-4927-9826-45fc03d3bc42"

[[r2_buckets]]
binding = "R2"
bucket_name = "notes-bucket"

[triggers]
crons = []

[[triggers.r2]]
bucket = "notes-bucket"
